# ─────────────────────────╮ 
# Oh My Posh configuration │
# ─────────────────────────╯
# @jvdcf
# Inspired from Dreams of Autonomy (https://www.youtube.com/watch?v=9U8LCjuQzdc)

#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'os'
    style = 'diamond'
    leading_diamond = ''
    background = 'blue'
    foreground = 'black'
    template = '{{ .Icon }} '

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    background = 'black'
    foreground = 'white'
    template = " \ue5fe {{ .Path }} "

    [blocks.segments.properties]
      style = 'agnoster_short'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = 'black'
    background = 'green'
    background_templates = [
      '{{ if or (.Working.Changed) (.Staging.Changed) }}yellow{{ end }}',
      '{{ if and (gt .Ahead 0) (gt .Behind 0) }}red{{ end }}',
      '{{ if gt .Ahead 0 }}red{{ end }}',
      '{{ if gt .Behind 0 }}red{{ end }}'
    ]
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} {{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}'

    [blocks.segments.properties]
      branch_icon = "\ue725 "
      cherry_pisk_icon = "\ue29b "
      commit_icon = "\uf417 "
      merge_icon = "\ue727 "
      no_commits_icon = "\uf0c3 "
      rebase_icon = "\ue728 "
      revert_icon = "\uf0e2 "
      tag_icon = "\uf412 "
      fetch_status = true

  [[blocks.segments]]
    type = 'executiontime'
    style = 'powerline'
    powerline_symbol = ''
    foreground = 'black'
    background = 'cyan'
    template = " \u29d7 {{ .FormattedMs }} "

    [blocks.segments.properties]
      threshold = 500

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}green{{end}}",
    ]
    background = 'transparent'
    template = '>'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}green{{end}}",
  ]
  background = 'transparent'
  template = '> '

[secondary_prompt]
  foreground = 'green'
  background = 'transparent'
  template = '>> '

