theme = "catppuccin_frappe"

[editor]
bufferline = "multiple"
line-number = "relative"
rulers = [80]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control"]

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "disable"

[editor.soft-wrap]
enable = true

[editor.auto-save]
focus-lost = true
after-delay.enable = true

[editor.file-picker]
hidden = false

[keys.normal]
C-g = [
    ":write-all",
    ":new",
    ":insert-output lazygit",
    ":buffer-close!",
    ":redraw",
    ":reload-all"
]
